secrets:
  db_url:
    file: ./db_url.txt
  jwt_secret:
    file: ./jwt_secret.txt

services:
  devcontainer:
    image: mcr.microsoft.com/devcontainers/typescript-node:1-22-bookworm
    volumes:
      - ../..:/workspaces:cached
    environment:
      - SERVER_PORT=3001
      - SERVER_JWT_SECRET_FILE=/run/secrets/jwt_secret
      - SERVER_DATABASE_URL_FILE=/run/secrets/db_url
    network_mode: service:db
    command: sleep infinity
    secrets:
      - db_url
      - jwt_secret

  db:
    image: postgres:alpine
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=varse
      - POSTGRES_PASSWORD=password

  pgadmin:
    image: dpage/pgadmin4:latest
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    ports:
      - 8080
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@varse.dev
      - PGADMIN_DEFAULT_PASSWORD=o83756gakafyg
      - PGADMIN_DISABLE_POSTFIX=1
      - PGADMIN_LISTEN_PORT=8080
    restart: unless-stopped

volumes:
  postgres-data: