name: Prod Builds

on:
  push:
    branches:
      - master
    paths:
      - "app/**"
      - "server/**"
  workflow_dispatch:

env:
  REGISTRY: nublar.azurecr.io

jobs:
  services:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ matrix.service.name }}
      cancel-in-progress: true
    strategy:
      matrix:
        service:
          - { name: "app", path: "app" }
          - { name: "api", path: "server" }
    steps:
      - uses: docker/setup-buildx-action@v3
        name: Set up Docker Buildx

      - uses: docker/login-action@v3
        name: Log into registry ${{ env.REGISTRY }}
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.REGISTRY_USER }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - uses: docker/metadata-action@v5
        id: image-metadata
        name: Extract metadata
        with:
          images: ${{ env.REGISTRY }}/varse/${{ matrix.service.name }}
          tags: |
            type=ref,event=branch
            type=ref,event=tag

      - uses: docker/build-push-action@v5
        id: build-and-push-python
        name: Build and push
        with:
          context: ${{ matrix.service.path }}
          push: true
          tags: ${{ steps.image-metadata.outputs.tags }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
